### ISSUE TITLE
practica 6

### ISSUE THREAD

**Issue by DamGL** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-damaris-equipo#2]
[Practica 6 app con realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-damaris-equipo/files/8604806/Practica.6.app.con.realidad.aumentada.pdf)

**Comment by ThorSampy** [comment]
El reporte esta completo y en forma 
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
